---
apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: app1
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
      nodePort: 30008
  selector:
    app: echo-server
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: echo-service
#   namespace: app1
# spec:
#   ports:
#     - name: http-port
#       port: 80
#       targetPort: http-port
#       protocol: TCP
#   selector:
#     app: echo-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: echoserver
  name: echo-service
  namespace: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/target-type: 'instance'
spec:
  ingressClassName: alb
  rules:
    - host: app.apps.dscott.sugn.p1.openshiftapps.com
      http:
        paths:
          - backend:
              service:
                name: echo-service
                port:
                  number: 80
            path: /
            pathType: Exact
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: echoserver
#   name: echo-service
#   namespace: app1
# spec:
#   host: apps.dscott.d2do.p1.openshiftapps.com
#   path: /
#   port:
#     targetPort: 80
#   to:
#     kind: Service
#     name: echo-service
#     weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: app2
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
      nodePort: 30007
  selector:
    app: echo-server
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: echo-service
#   namespace: app2
# spec:
#   ports:
#     - name: http-port
#       port: 80
#       targetPort: http-port
#       protocol: TCP
#   selector:
#     app: echo-server
# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: echoserver
#   name: echo-service
#   namespace: app2
# spec:
#   host: apps.dscott.d2do.p1.openshiftapps.com
#   path: /
#   port:
#     targetPort: 80
#   to:
#     kind: Service
#     name: echo-service
#     weight: 100
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: echoserver
  name: echo-service
  namespace: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/target-type: 'instance'
spec:
  ingressClassName: alb
  rules:
    - host: app.apps.dscott.sugn.p1.openshiftapps.com
      http:
        paths:
          - backend:
              service:
                name: echo-service
                port:
                  number: 80
            path: /
            pathType: Exact
