apiVersion: v1
kind: Secret
metadata:
  name: aws-load-balancer-operator
  namespace: aws-load-balancer-operator
stringData:
  credentials: |
    [default]
    role_arn = {{ .Values.role_arn }}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token