---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-dscott-host
---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-dscott-host-canary
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: poc-dscott-host
  namespace: openshift-ingress-operator
spec:
  routeAdmission:
    namespaceOwnership: InterNamespaceAllowed
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: mobb-infra-primary-cert-bundle-secret
  domain: host-valid.mydomain.com
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
  replicas: 2
  tuningOptions: {}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: poc-dscott-host-canary
  namespace: openshift-ingress-operator
spec:
  routeAdmission:
    namespaceOwnership: InterNamespaceAllowed
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: mobb-infra-primary-cert-bundle-secret
  domain: host-valid.canary.mydomain.com
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
  replicas: 2
  tuningOptions: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: poc-dscott-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: poc-dscott-host
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: echoserver
  name: echo-service
  namespace: poc-dscott-host
spec:
  host: app.host-valid.mydomain.com
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: echo-service
    weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: poc-dscott-host-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: poc-dscott-host-canary
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: echoserver
  name: echo-service
  namespace: poc-dscott-host-canary
spec:
  host: app.host-valid.canary.mydomain.com
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: echo-service
    weight: 100
